FROM python:3.9

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем скрипты
COPY generate_data.py generate_data.py
COPY config.py config.py

CMD ["python", "generate_data.py"]
